package control

import (
	"errors"
	"sort"
	"strings"
)

type UseCaseTemplate struct {
	ID                string            `json:"id"`
	Name              string            `json:"name"`
	Scenario          string            `json:"scenario"`
	Description       string            `json:"description"`
	RecommendedTags   []string          `json:"recommended_tags,omitempty"`
	ScaffoldFiles     map[string]string `json:"scaffold_files,omitempty"`
	WorkflowStepFiles []string          `json:"workflow_step_files,omitempty"`
	RunbookConfigFile string            `json:"runbook_config_file,omitempty"`
}

type UseCaseTemplateCatalog struct {
	templates map[string]UseCaseTemplate
}

func NewUseCaseTemplateCatalog() *UseCaseTemplateCatalog {
	items := []UseCaseTemplate{
		newUseCaseTemplate("blue-green-release", "Blue/Green Release", "release-rollout", "Application release with blue/green promotion and rollback gates.", []string{"blue-green", "release", "traffic-gate"}),
		newUseCaseTemplate("canary-release", "Canary Release", "release-rollout", "Progressive canary deployment with health-gated expansion.", []string{"canary", "release", "progressive"}),
		newUseCaseTemplate("rolling-release", "Rolling Release", "release-rollout", "Batch and percentage-based rolling deployment workflow.", []string{"rolling", "release", "batch"}),
		newUseCaseTemplate("zero-downtime-os-patching", "Zero-Downtime OS Patching", "patching", "Coordinated patching and reboot campaign with disruption budgets.", []string{"patching", "reboot", "maintenance"}),
		newUseCaseTemplate("certificate-rotation", "Certificate Rotation", "security-operations", "Fleet-wide certificate/trust store rotation with staged validation.", []string{"cert-rotation", "trust-store", "security"}),
		newUseCaseTemplate("database-schema-change", "Database Schema Change", "stateful-change", "Schema-change orchestration with preflight checks and rollback hooks.", []string{"database", "schema-change", "rollback"}),
		newUseCaseTemplate("disaster-recovery-cutover", "Disaster Recovery Cutover", "resilience", "Cutover/failback orchestration and post-recovery reconciliation.", []string{"dr", "cutover", "reconciliation"}),
		newUseCaseTemplate("emergency-vulnerability-remediation", "Emergency Vulnerability Remediation", "security-operations", "Rapid, guardrailed emergency remediation for critical vulnerabilities.", []string{"emergency", "vulnerability", "fleet"}),
		newUseCaseTemplate("seasonal-scale-operations", "Seasonal Scale Operations", "capacity-planning", "Scale-up/scale-down workflow with safety limits and validation.", []string{"seasonal", "capacity", "autoscale"}),
		newUseCaseTemplate("brownfield-modernization", "Brownfield Modernization", "migration", "Legacy-to-modern migration onboarding with incremental convergence.", []string{"brownfield", "migration", "onboarding"}),
		newUseCaseTemplate("ownership-transfer", "Service Ownership Transfer", "tenancy", "Service handoff and platform tenancy carve-out workflow.", []string{"ownership", "tenancy", "handoff"}),
	}

	templates := map[string]UseCaseTemplate{}
	for _, item := range items {
		templates[item.ID] = item
	}
	return &UseCaseTemplateCatalog{templates: templates}
}

func (c *UseCaseTemplateCatalog) List() []UseCaseTemplate {
	out := make([]UseCaseTemplate, 0, len(c.templates))
	for _, item := range c.templates {
		out = append(out, cloneUseCaseTemplate(item))
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func (c *UseCaseTemplateCatalog) Get(id string) (UseCaseTemplate, error) {
	id = strings.TrimSpace(id)
	item, ok := c.templates[id]
	if !ok {
		return UseCaseTemplate{}, errors.New("use-case template not found")
	}
	return cloneUseCaseTemplate(item), nil
}

func cloneUseCaseTemplate(item UseCaseTemplate) UseCaseTemplate {
	out := item
	out.RecommendedTags = append([]string{}, item.RecommendedTags...)
	out.WorkflowStepFiles = append([]string{}, item.WorkflowStepFiles...)
	out.ScaffoldFiles = map[string]string{}
	for path, content := range item.ScaffoldFiles {
		out.ScaffoldFiles[path] = content
	}
	return out
}

func newUseCaseTemplate(id, name, scenario, description string, tags []string) UseCaseTemplate {
	scaffold := map[string]string{
		"README.md": "# " + name + "\n\n" +
			"This use-case template is generated by Masterchef for " + scenario + " workflows.\n",
		"configs/preflight.yaml": `version: v0
inventory:
  hosts:
    - name: local-preflight
      transport: local
resources:
  - id: preflight-marker
    type: file
    host: local-preflight
    path: ./tmp/` + id + `-preflight.txt
    content: "preflight=ok\n"
`,
		"configs/apply.yaml": `version: v0
inventory:
  hosts:
    - name: local-apply
      transport: local
resources:
  - id: apply-marker
    type: file
    host: local-apply
    path: ./tmp/` + id + `-apply.txt
    content: "apply=ok\n"
`,
		"configs/verify.yaml": `version: v0
inventory:
  hosts:
    - name: local-verify
      transport: local
resources:
  - id: verify-marker
    type: file
    host: local-verify
    path: ./tmp/` + id + `-verify.txt
    content: "verify=ok\n"
`,
	}
	return UseCaseTemplate{
		ID:                id,
		Name:              name,
		Scenario:          scenario,
		Description:       description,
		RecommendedTags:   tags,
		ScaffoldFiles:     scaffold,
		WorkflowStepFiles: []string{"configs/preflight.yaml", "configs/apply.yaml", "configs/verify.yaml"},
		RunbookConfigFile: "configs/apply.yaml",
	}
}
